### ISSUE TITLE
20190330 issue url wrong?

### ISSUE THREAD

**Issue by wlnirvana** [duxingzhe/The-Economist-Audio-Downloader#1]
https://audiocdn.economist.com/sites/default/files/AudioArchive/2019/20190330/Issue_9136_20190330_The_Economist_Full_edition.zip is 404 at this moment.

**Comment by duxingzhe** [comment]
Sorry. It may changed, and I cannot fix it at this moment. You can download the audio edition from others and unzip the file to the directory.

**Comment by ddayzzz** [comment]
Maybe you can downlaod the all in one: [http://audiocdn.economist.com/sites/default/files/AudioArchive/2019/20190330/Issue_9136_20190330_The_Economist_Full_edition.m4a](http://audiocdn.economist.com/sites/default/files/AudioArchive/2019/20190330/Issue_9136_20190330_The_Economist_Full_edition.m4a)

**Comment by duxingzhe** [comment]
Thanks for your solution.

**Comment by ttyS0** [comment]
A really intricate and confused thing is that compressed media for Mar 30 are at http://audiocdn.economist.com/sites/default/files/AudioArchive/2019/20190330/Issue_9136_20190330_The_Economist_Full_Edition.zip
The only difference is the "E" and "e". Enjoy :)

**Comment by duxingzhe** [comment]
Thanks. That's nice.
