### ISSUE TITLE
你的这东西用不了

### ISSUE THREAD

**Issue by ultramarinus** [duxingzhe/The-Economist-Audio-Downloader#5]
你设置的第一个要期刊号，比如经济学人2024年5月18日发布的杂志期刊号是MAY 18TH 2024，你设置的这种又打不了英文字母，只能打数字，真搞不懂你设置的期刊号是什么。而且软件还闪退。

**Comment by duxingzhe** [comment]
现在只更新基础控件，不维护了。你可以自己下载源码修改。期刊号在pdf里面，是issue，不是May 18th 2024，这个是发行时间。
